package com.fran.htaxonomy.entidades;

// default package
// Generated 15 dic 2022 20:27:33 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Objects;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Species generated by hbm2java
 */
@Entity
@Table(name = "species", catalog = "taxonomy")
public class Species implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Family family;
	private String name;
	private boolean researchgradle;
	private String urlimage;

	public Species() {
	}

	public Species(Family family, String name, boolean researchgradle) {
		this.family = family;
		this.name = name;
		this.researchgradle = researchgradle;
	}

	public Species(Family family, String name, boolean researchgradle, String urlimage) {
		this.family = family;
		this.name = name;
		this.researchgradle = researchgradle;
		this.urlimage = urlimage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "family", nullable = false)
	public Family getFamily() {
		return this.family;
	}

	public void setFamily(Family family) {
		this.family = family;
	}

	@Column(name = "name", nullable = false, length = 300)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "researchgradle", nullable = false)
	public boolean isResearchgradle() {
		return this.researchgradle;
	}

	public void setResearchgradle(boolean researchgradle) {
		this.researchgradle = researchgradle;
	}

	@Column(name = "urlimage", length = 300)
	public String getUrlimage() {
		return this.urlimage;
	}

	public void setUrlimage(String urlimage) {
		this.urlimage = urlimage;
	}

	@Override
	public String toString() {
		return "Species [id=" + id + ", name=" + name + ", researchgradle=" + researchgradle
				+ ", urlimage=" + urlimage + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Species other = (Species) obj;
		return Objects.equals(id, other.id);
	}

}
